# Generated by Django 3.2.9 on 2021-11-18 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cam_ip', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('pwd', models.CharField(max_length=30)),
                ('authority', models.CharField(choices=[('0', 'User'), ('1', 'Admin')], default='0', max_length=2)),
                ('cam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.cam', verbose_name='相机id')),
            ],
        ),
    ]
