# Generated by Django 3.2.9 on 2021-11-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_cam_rtsp_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cam',
            name='cam_ip',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cam',
            name='rtsp_ip',
            field=models.CharField(max_length=250),
        ),
    ]
